IOmanip lab tasks done
yura29/cxx-tasks pull request #1
Opened 2018-10-18 11:01 UTC by yura29

2018-10-19 05:32 UTC, igsha requested changes
@yura29, всё норм. Есть небольшое замечание, но оно не повлияет на баллы. Тем не менее на него надо как-то ответить или исправить, чтобы я замёржил в мастер.

2018-10-19 05:32 UTC, igsha commented on iomanip/include/iomanip.hpp
> +typedef struct add_proxy_1
В чём смысл этого `typedef`?

2018-10-21 15:58 UTC, yura29 commented on iomanip/include/iomanip.hpp
> +typedef struct add_proxy_1
Я сделал typedef, так как думал, что в с++, как и в чистом с при использовании структур надо писать везде писать struct [strcut_name]
typedef был введен для сокращения

2018-10-21 16:21 UTC, igsha commented on iomanip/include/iomanip.hpp
> +typedef struct add_proxy_1
Не, в c++, наоборот, такого не пишут. Ключевое слово `typedef` пришло из C и скорее всего скоро утратит своё значение, так расширилось применение `using`.

2018-10-21 18:35 UTC, yura29 commented
@igsha, щамечания исправил

2018-10-21 19:15 UTC, igsha approved these changes

2018-10-21 19:16 UTC, merged