Answers for questions
yura29/cxx-tasks pull request #10
Opened 2018-12-24 14:37 UTC by yura29

2018-12-24 16:52 UTC, yura29 commented
@igsha, старый pull request был утрачен. Я сделал новый, замечания исправил

2018-12-24 18:10 UTC, igsha requested changes
На 5-ку (86 беллов) надо ответить ещё на 2 вопроса.

2018-12-24 18:10 UTC, igsha commented on parser/include/json.hpp
> +        //! class array_ is same syntax as struct array_. But in case of class keyword class is not necessary
```cpp
template<class T>
void func()
{
    std::cout << "do nothing\n";
}

int main() 
{
    func<struct abc>(); // Норм, пишет `do nothing`
    func<cba>(); // Ошибка: main.cpp:14:10: error: 'cba' was not declared in this scope
}
```
Если написать перед `cba` написать слово `class` то всё станет компилироваться без ошибок.

2018-12-24 23:09 UTC, yura29 commented
@igsha, ответ исправил. Новые ответы добавил

2018-12-25 15:42 UTC, igsha requested changes
С вопросами ок, но в репозитории появился какой-то посторонний файл

2018-12-25 15:42 UTC, igsha commented on parser/include/catch.hpp
> +/*
а это что за файл?

2018-12-25 15:53 UTC, yura29 commented
@igsha, под виндой компилил. catch руками в проект положил и случайно в коммит добавил. Уже удалил

2018-12-25 16:35 UTC, igsha approved these changes

2018-12-25 16:35 UTC, merged