Iterator tasks are done
yura29/cxx-tasks pull request #3
Opened 2018-11-02 13:20 UTC by yura29

```
Test project /home/ybogomolov/cxx-tasks/build
    Start 1: tests_iterator:iterator::operations
1/4 Test #1: tests_iterator:iterator::operations .........   Passed    0.00 sec
    Start 2: tests_iterator:iterator::write
2/4 Test #2: tests_iterator:iterator::write ..............   Passed    0.00 sec
    Start 3: tests_iterator:iterator::copy_from_vector
3/4 Test #3: tests_iterator:iterator::copy_from_vector ...   Passed    0.00 sec
    Start 4: tests_iterator:iterator::copy_to_vector
4/4 Test #4: tests_iterator:iterator::copy_to_vector .....   Passed    0.00 sec

100% tests passed, 0 tests failed out of 4

Label Time Summary:
tests_iterator    =   0.01 sec*proc (4 tests)

```

2018-11-02 20:11 UTC, igsha requested changes
Это не самый удачный вариант (так как `index_` и `base_reference()` имеют примерно одинаковую функциональность), но вроде бы рабочий. Необходимо поправить замечания.

2018-11-02 20:11 UTC, igsha commented on iterator/include/iterator.hpp
> +    void advance(ptrdiff_t n)
вместо `ptrdiff_t` лучше использовать то, что есть у итератора уже: `typename image_iterator::difference_type`

2018-11-02 20:11 UTC, igsha commented on iterator/include/iterator.hpp
> +            double tmp = (double)(abs(n) - rest) / width_;
непонятно, зачем тут флотовая арифметика. Если нужен остаток, то лучше воспользоваться, например, `std::div`

2018-11-02 20:11 UTC, igsha commented on iterator/include/iterator.hpp
> +            tmp = abs(tmp);
Зачем тут модуль? Разве результат может получится отрицательным? Зачем тогда в `if`-е проверять, что `abs(n) > rest`?

2018-11-02 20:11 UTC, igsha commented on iterator/include/iterator.hpp
> +            stride_count = (tmp - (int)tmp == 0) ? tmp : tmp + 1;
Если остаток равен 0?
```cpp
stride_count = tmp.rem == 0 ? tmp.quot : tmp.quot + 1;
```

2018-11-02 20:11 UTC, igsha commented on iterator/include/iterator.hpp
> +        int n = x.base() - this->base();
`int`-ами плохо оперировать, так как у `x.base() - this->base()` есть тип `typename image_iterator::difference_type` или `auto`

2018-11-11 16:25 UTC, ybogo commented on iterator/include/iterator.hpp
> +            double tmp = (double)(abs(n) - rest) / width_;
@igsha, здесь не остаток
Здесь вычисляется кол-во элементов до конца(или начала) строки

2018-11-11 16:26 UTC, ybogo commented on iterator/include/iterator.hpp
> +            stride_count = (tmp - (int)tmp == 0) ? tmp : tmp + 1;
@igsha, есть какой-то специальный класс, в котором можно брать дробную часть и целую через обращение к полям?

2018-11-11 16:26 UTC, ybogo commented
@igsha, замечания исправил

2018-11-11 17:27 UTC, igsha requested changes

2018-11-11 17:27 UTC, igsha commented on iterator/include/iterator.hpp
> +            stride_count = (tmp - (int)tmp == 0) ? tmp : tmp + 1;
@yura29, да, это [std::div_t](https://en.cppreference.com/w/cpp/numeric/math/div)

2018-11-11 17:27 UTC, igsha commented on iterator/include/iterator.hpp
> +            double tmp = (double)(abs(n) - rest) / width_;
я и не писал, что это остаток. Остаток нужен на следующей строке, его можно получить, не прибегая к `double`

2018-11-16 10:20 UTC, yura29 commented
@igsha , исправил

2018-11-16 12:00 UTC, igsha approved these changes

2018-11-16 12:00 UTC, merged