type_map tasks are done
yura29/cxx-tasks pull request #4
Opened 2018-11-16 11:37 UTC by yura29

```
Test project /home/ybogomolov/cxx-tasks/build
    Start 1: tests_type_map:type_map::int
1/2 Test #1: tests_type_map:type_map::int .....   Passed    0.00 sec
    Start 2: tests_type_map:type_map::enum
2/2 Test #2: tests_type_map:type_map::enum ....   Passed    0.00 sec

100% tests passed, 0 tests failed out of 2

Label Time Summary:
tests_type_map    =   0.00 sec*proc (2 tests)

Total Test time (real) =   0.00 sec

```

2018-11-16 12:05 UTC, igsha requested changes
Требуются исправления. Работа защищается на 12 неделе, вместо 11 => -1 балл

2018-11-16 12:05 UTC, igsha commented on type_map/include/type_map.hpp
> +    template<typename T, class TypeMap>
здесь должна быть одна функция, а логика констрантности объекта должна перейти в `type_map`

2018-11-17 10:25 UTC, ybogo commented
@igsha, исправил

2018-11-18 13:16 UTC, igsha approved these changes

2018-11-18 13:16 UTC, merged