parser csv tasks are done
yura29/cxx-tasks pull request #5
Opened 2018-11-17 15:01 UTC by yura29

```
Test project /home/ybogomolov/cxx-tasks/build
    Start 1: tests_parser:csv::string
1/5 Test #1: tests_parser:csv::string .........   Passed    0.00 sec
    Start 2: tests_parser:csv::cell
2/5 Test #2: tests_parser:csv::cell ...........   Passed    0.00 sec
    Start 3: tests_parser:csv::row
3/5 Test #3: tests_parser:csv::row ............   Passed    0.00 sec
    Start 4: tests_parser:csv::csv
4/5 Test #4: tests_parser:csv::csv ............   Passed    0.00 sec
    Start 5: tests_parser:csv::operator_csv
5/5 Test #5: tests_parser:csv::operator_csv ...   Passed    0.00 sec

```

2018-11-18 15:26 UTC, igsha requested changes
Есть пара недочётов

2018-11-18 15:26 UTC, igsha commented on parser/include/quoted_string.hpp
> +    auto quoted_string = x3::lexeme['"' >> *(~x3::char_('"')) >> '"'];;
Они все должны быть константами, иначе не собирается:
```
[ 25%] Linking CXX executable tests_parser
CMakeFiles/tests_parser.dir/tests/quoted_string.cpp.o:(.bss+0x0): multiple definition of `parser::quoted_string'
CMakeFiles/tests_parser.dir/tests/csv.cpp.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/tests_parser.dir/build.make:115: tests_parser] Error 1
make[1]: *** [CMakeFiles/Makefile2:393: CMakeFiles/tests_parser.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
```

2018-11-18 15:26 UTC, igsha commented on parser/include/csv.hpp
> +                 = cell >> *(',' >> cell);
лучше воспользоваться оператором `%`

2018-11-19 11:55 UTC, yura29 commented
@igsha, испарвил

2018-11-19 12:14 UTC, igsha commented
@yura29, есть один необязательный тест
```
-------------------------------------------------------------------------------
quoted_string::quote
-------------------------------------------------------------------------------
/tmp/cxx-tasks/parser/tests/quoted_string.cpp:32
...............................................................................

/tmp/cxx-tasks/parser/tests/quoted_string.cpp:32: FAILED:
due to unexpected exception with message:
  Trailing symbols, difference: 8
```
Можно его сделать, тогда будут полные 12 баллов за это задание.

2018-11-19 13:18 UTC, yura29 commented
@igsha, исправил

2018-11-19 16:04 UTC, igsha approved these changes

2018-11-19 16:04 UTC, merged