JSON parser tasks are done
yura29/cxx-tasks pull request #6
Opened 2018-12-07 13:42 UTC by yura29

```
Test project /home/ybogomolov/cxx-tasks/build
      Start  1: tests_parser:csv::string
 1/19 Test  #1: tests_parser:csv::string .......................   Passed    0.00 sec
      Start  2: tests_parser:csv::cell
 2/19 Test  #2: tests_parser:csv::cell .........................   Passed    0.00 sec
      Start  3: tests_parser:csv::row
 3/19 Test  #3: tests_parser:csv::row ..........................   Passed    0.00 sec
      Start  4: tests_parser:csv::csv
 4/19 Test  #4: tests_parser:csv::csv ..........................   Passed    0.00 sec
      Start  5: tests_parser:csv::operator_csv
 5/19 Test  #5: tests_parser:csv::operator_csv .................   Passed    0.00 sec
      Start  6: tests_parser:json::number
 6/19 Test  #6: tests_parser:json::number ......................   Passed    0.00 sec
      Start  7: tests_parser:json::nullable
 7/19 Test  #7: tests_parser:json::nullable ....................   Passed    0.00 sec
      Start  8: tests_parser:json::array
 8/19 Test  #8: tests_parser:json::array .......................   Passed    0.00 sec
      Start  9: tests_parser:json::object
 9/19 Test  #9: tests_parser:json::object ......................   Passed    0.00 sec
      Start 10: tests_parser:json::json
10/19 Test #10: tests_parser:json::json ........................   Passed    0.00 sec
      Start 11: tests_parser:json::operator_json
11/19 Test #11: tests_parser:json::operator_json ...............   Passed    0.00 sec
      Start 12: tests_parser:quoted_string::spaces
12/19 Test #12: tests_parser:quoted_string::spaces .............   Passed    0.00 sec
      Start 13: tests_parser:quoted_string::comma
13/19 Test #13: tests_parser:quoted_string::comma ..............   Passed    0.00 sec
      Start 14: tests_parser:quoted_string::quote
14/19 Test #14: tests_parser:quoted_string::quote ..............   Passed    0.00 sec
      Start 15: tests_parser:quoted_string::newline
15/19 Test #15: tests_parser:quoted_string::newline ............   Passed    0.00 sec
      Start 16: tests_parser:quoted_string::failure
16/19 Test #16: tests_parser:quoted_string::failure ............   Passed    0.00 sec
      Start 17: tests_parser:variant_decorator::constructors
17/19 Test #17: tests_parser:variant_decorator::constructors ...   Passed    0.00 sec
      Start 18: tests_parser:variant_decorator::as
18/19 Test #18: tests_parser:variant_decorator::as .............   Passed    0.00 sec
      Start 19: tests_parser:variant_decorator::const
19/19 Test #19: tests_parser:variant_decorator::const ..........   Passed    0.00 sec

100% tests passed, 0 tests failed out of 19

Label Time Summary:
!mayfail        =   0.00 sec*proc (3 tests)
tests_parser    =   0.04 sec*proc (19 tests)

Total Test time (real) =   0.05 sec

```

2018-12-07 15:40 UTC, igsha requested changes
Требуются доработки.
-2 балла за просрок.

2018-12-07 15:40 UTC, igsha commented on parser/include/variant_decorator.hpp
> +    variant_decorator& operator=(variant_decorator const&)=default;
все операторы= и конструкторы должны были прийти через `using`, разве это не так?

2018-12-07 15:40 UTC, igsha commented on parser/include/variant_decorator.hpp
> +    const T& as() const
Реализуйте один из методов `as` через другой. Нужно догадаться, какой метод (константный или нет) следует взять за базовую реализацию.

2018-12-09 10:55 UTC, yura29 commented on parser/include/variant_decorator.hpp
> +    variant_decorator& operator=(variant_decorator const&)=default;
Да, но если использовать только using, то я получаю ошибку use of deleted function
```
/usr/include/c++/7/bits/stl_construct.h:75:7: error: use of deleted function ‘variant_decorator<int, float, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::nullptr_t, types::json::array, types::json::object>::variant_decorator(const variant_decorator<int, float, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::nullptr_t, types::json::array, types::json::object>&)’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ybogomolov/cxx-tasks/parser/include/json.hpp:20:0,
                 from /home/ybogomolov/cxx-tasks/parser/tests/json.cpp:8:

```

2018-12-09 10:57 UTC, yura29 commented
@igsha, замечания исправил

2018-12-09 13:29 UTC, igsha requested changes
Требуются разъяснения.

2018-12-09 13:29 UTC, igsha commented on parser/include/variant_decorator.hpp
> +    variant_decorator& operator=(variant_decorator & o) {
Этот оператор лишний? Оператор = не должен изменять правый объект от знака присваивания, значит, объект должен быть константным.

2018-12-09 14:45 UTC, yura29 commented on parser/include/variant_decorator.hpp
> +    variant_decorator& operator=(variant_decorator & o) {
Да, этот оператор лишний
Удалил

2018-12-09 14:45 UTC, yura29 commented
@igsha, замечания исправил

2018-12-09 15:37 UTC, igsha requested changes

2018-12-09 15:37 UTC, igsha commented on parser/include/json.hpp
> +        types::json::json operator "" _json(const char* s, size_t size)
А где `size` используется? Будет ошибка `unused argument`

2018-12-09 15:37 UTC, igsha commented on parser/include/variant_decorator.hpp
> +    variant_decorator& operator=(variant_decorator & o) {
Где? Ничего не изменилось

2018-12-10 11:02 UTC, yura29 commented
@igsha, забыл файлы в коммит добавить
Теперь точно исправил

2018-12-10 15:34 UTC, igsha approved these changes

2018-12-10 15:35 UTC, igsha commented
@yura29, необходимо сделать рибейз

2018-12-15 12:38 UTC, yura29 commented
@igsha, ребейзнулся

2018-12-15 13:28 UTC, merged